version: '3'
services:
    web:
        build: .
        command: npm run dev
        # The working directory is mounted as a volume, so the changes on it are detected by nodemon when running the dev script
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports: 
            - "3000:3000"
        env_file:
            - config/dev.env
            # To use the Docker Compose MongoDB Container as the system database, set the following variable into the config/dev.env file:
            # (The hostname part ("db") in the URL, belongs to the MongoDB container)
            # - DB_PATH=mongodb://db:27017/turnsystem
    # The following container allows to run the tests in a separated environment, so it's not neccesary to send the test.env file to the container
    web_test:
        build: .
        command: npm test
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - config/test.env
    db:
        # Last stable version
        image: mongo:4.2.6
        ports:
            # Expose the container port to the host
            - 27017:27017
