version: '3'
services:
    web:
        build: .
        command: npm run dev
        volumes:
            # The working directory is mounted as a volume, so the changes on it are detected by nodemon when running the dev script
            - ./:/usr/src/app
        ports: 
            - "3000:3000"
        environment:
            # The hostname in the URL, belongs to the mongodb container defined next
            - DB_PATH=mongodb://mongodb:27017/turnsystem
    mongodb:
        # Last stable version
        image: mongo:4.2.5
        ports:
            # Expose the container port to the host
            - 27017:27017
