version: '3'
services:
    web:
        build: .
        command: npm run dev
        volumes:
            # The working directory is mounted as a volume, so the changes on it are detected by nodemon when running the dev script
            - ./:/usr/src/app
        ports: 
            - "3000:3000"
        environment:
            - DB_PATH=mongodb://127.0.0.1:27017/turnsystem
    mongodb:
        # Last stable version
        image: mongo:4.2.5
        ports: 
            - 27017:27017
